timeout: 0

/Nox Plasma Bring-up
    protocol: limine
    path: boot():/boot/twilight.elf
    cmdline: os_name=Nox plasma_bringup=1
    module_path: boot():/boot/plasma-rootfs.cpio
    module_string: nox-rootfs
